server:
  port: 8000

spring:
  application:
    name: order-service
  # 指定当前环境
  profiles:
    active: prod
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        # 关闭配置中心检查
        import-check:
          enabled: false
        # 指定命名空间。默认使用public
        namespace: ${spring.profiles.active:public}
    sentinel:
      transport:
        # sentinel 控制台
        dashboard: localhost:8080
      # 开启提前加载
      eager: true
      web-context-unify: false

# openfeign 配置
feign:
  client:
    config:
      # 默认配置
      default:
        logger-level: full
        connect-timeout: 2000
        read-timeout: 2000
      # 指定feign客户端配置
      product-service:
        logger-level: full
        connect-timeout: 5000
        read-timeout: 5000
  # 开启服务熔断
  sentinel:
    enabled: true

logging:
  level:
    root: info
    com.zero.order.feign : debug
---
spring:
  config:
    import:
      - nacos:common.yml?group=order
      - nacos:db.yml?group=order
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.yml?group=order
      - nacos:db.yml?group=order
      - nacos:test.yml?group=order
    activate:
      on-profile: test

---
spring:
  config:
    import:
      - nacos:common.yml?group=order
      - nacos:db.yml?group=order
      - nacos:prod.yml?group=order
    activate:
      on-profile: prod